apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  ports:
  - port: 3306
  selector:
    app: db
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  selector:
    matchLabels:
      app: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - image: mariadb:10.2
        name: db
        env:
          # não faça isso em produção, utilize secrets
        - name: MYSQL_ROOT_PASSWORD
          value: test
        - name: MYSQL_USER
          value: user
        - name: MYSQL_PASSWORD
          value: test
        - name: MYSQL_DATABASE
          value: sistema
        ports:
        - containerPort: 3306
          name: db
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim